### PR TITLE
Allow 2.12.0 dev SDK versions

### PR DESCRIPTION
**Pull request by natebosch**
Drop dependency overrides and update deps to `-nullsafety` versions.

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by natebosch** [comment]
This is not safe to publish.

**Comment by jakemac53** [comment]
> This is not safe to publish.

What is the issue here? Failures in the sdk/internally or something?

**Comment by natebosch** [comment]
Only that this version has code changes that aren't tested internally. Oncw the next SDK roll happens it should be good to go.

**Comment by jakemac53** [comment]
This looks up to date now.

**Pull request merged**
