### PR TITLE
Update the README.

### LINKED ISSUE #16: README doesn't show the awesome that is this library
Hi,

This package is great. But the README makes it look like it has a single thing: ZipStream.

We might consider blanking out the README and just point to the docs, or we could add more "what is this thing and what can it do for me?" in the README.

We're way way way way underselling this library in the README :)

### PR DESCRIPTION
**Pull request by nex3**
Closes #16

### CODE REVIEW

**Comment by nex3** [comment]
cc @sethladd

**Comment by sethladd** [comment]
lgtm

thanks! much more impressive :)

**Comment by matanlurey** [comment]
Awesome!

**Comment by nex3** [comment]
@lrhn Ping!

**Pull request merged**
