### PR TITLE
Run tests in DDC w/ incremental caching

### PR DESCRIPTION
**Pull request by matanlurey**
Taken from here:
https://github.com/dart-lang/mockito/blob/master/.travis.yml

Example builds/tests are super fast:
https://travis-ci.org/dart-lang/mockito/builds/347054827

### CODE REVIEW

**Comment by matanlurey** [comment]
Well good news - this catches that `fake_async` is broken.

What are we doing here? @srawlins @natebosch @munificent

**Comment by natebosch** [comment]
https://github.com/dart-lang/async/issues/49

I think we're going to need to make a decision whether we want to take over the fake_async package since the author is not active.

cc @nex3 @kevmoo

**Comment by matanlurey** [comment]
Can we temporarily use Quiver's FakeAsync (the original)? I think it works.

**Comment by matanlurey** [comment]
Ping @nex3 @natebosch @kevmoo

**Comment by natebosch** [comment]
I think we have permission to take over package:fake_async and package:clock.

Our plan is to move the code from quiver to these packages. We want to have only 1 copy and the ones in quiver have more users so we're better off starting from that. Use an `export` to make the migration to that import easier/incremental.

I don't know if we have anyone slotted to take on the work though. In practice that does mean migrating to the package:quiver version of this class - but if we can do it without the (temporary) import to quiver that would be optimal.

**Comment by nex3** [comment]
I'm happy to do the migration.

**Comment by natebosch** [comment]
I think that the `fake_async` and `clock` stuff has all been migrated? At least the tests seem to be passing in Dart 2 runtime.

I don't think that there is still value in this change now that we're getting Dart 2 runtime testing in the VM. @matanlurey - please reopen if you disagree and still want to pursue DDC tests in this repo.

**Pull request closed without merging**
